name: CI_Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "windows-latest" ]
    steps:
    - uses: actions/checkout@v2
    - name: make bin on ${{ matrix.os }}
      run: | 
        mkdir build 
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
        make bin
    - name: test bin on ${{ matrix.os }}
      run: |
        cd build
        ls -la
        ctest -R bin --verbose

